### ISSUE TITLE
Notice: Undefined variable: 

### ISSUE THREAD

**Issue by ivan-s-1** [dzhuryn/collection#1]
Notice: Undefined variable: controllerConfig in /var/www/local-website/evo-creator.ru/assets/modules/collections/collections.plugin.php on line 43 Notice: Undefined variable: treeConfig in /var/www/local-website/evo-creator.ru/assets/modules/collections/collections.plugin.php on line 71 Notice: Undefined variable: treeOnClickModuleConfig in /var/www/local-website/evo-creator.ru/assets/modules/collections/collections.plugin.php on line 73

- Версия Evolution CMS 2.0.0-alpha
- php 7.1

**Comment by dmitriy71n** [comment]
- Evolution CMS 1.4.31
- PHP 8.1

Warning: Undefined array key "parent" in /www/site.name/assets/modules/collections/collections.module.php on line 27
Warning: Undefined array key "editor" in /www/site.name/assets/modules/collections/controllers/BaseController.php on line 277
Warning: Undefined array key "caption" in /www/site.name/assets/modules/collections/controllers/BaseController.php on line 274
Warning: Undefined array key "editor" in /www/site.name/assets/modules/collections/controllers/BaseController.php on line 277
